### ISSUE TITLE
Code Run: Object does not match target type.

### ISSUE THREAD

**Issue by JayVDZ** [sorengranfeldt/fimactivitylibrary#2]
Hello! I'm using the Code Run activity to good effect, it works most of the time, but every now and then a request fails with the error:

`Object does not match target type.`

The activity is configured as:
Reference (DLL's): System.dll
Parameters: [//Target/someAttribute]
Code:

```
using System;
public class FimDynamicClass
{
    public object FIMDynamicFunction(object someAttribute)
    {
        if (someAttribute != null)
        {
            return someAttribute;
         }
         else
        {
            return DateTime.UtcNow;
         }
    }
}
```

someAttribute is of type Datetime in MIM schema.
The error seems like it might be coming from a Reflection operation in the library? Going by:
https://stackoverflow.com/questions/19101222/c-sharp-reflection-object-does-not-match-target-type

Any ideas/suggestions?

**Comment by sorengranfeldt** [comment]
All I can think of is that some rogue objects are passed to your workflow and they somehow does not match what you're applying to them. It is a little hard to troubleshoot without any more information than the code. I'd check event log and trace logs for more information if I was you. However, that goes beyond my support on this library.
